name = "NonuniformFFTs"
uuid = "cd96f58b-6017-4a02-bb9e-f4d81626177f"
authors = ["Juan Ignacio Polanco <juan-ignacio.polanco@cnrs.fr>"]
version = "0.3.18"

[deps]
AbstractNFFTs = "7f219486-4aa7-41d6-80a7-e08ef20ceed7"
Bessels = "0e736298-9ec6-45e8-9647-e4fc86a2fe38"
Bumper = "8ce10254-0962-460f-a3d8-1f77fea1446e"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Static = "aedffcd0-7271-4cad-89d0-dc628f76c6d3"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[compat]
AbstractNFFTs = "0.8.2"
Bessels = "0.2"
Bumper = "0.6, 0.7"
FFTW = "1.7"
LinearAlgebra = "1.9"
PrecompileTools = "1.2"
Static = "0.8, 1"
StaticArrays = "1.7"
StructArrays = "0.6"
TimerOutputs = "0.5"
julia = "1.9"
