name = "NonuniformFFTs"
uuid = "cd96f58b-6017-4a02-bb9e-f4d81626177f"
authors = ["Juan Ignacio Polanco <juan-ignacio.polanco@cnrs.fr>"]
version = "0.6.1"

[deps]
AbstractFFTs = "621f4979-c628-5d54-868e-fcf4e3e8185c"
AbstractNFFTs = "7f219486-4aa7-41d6-80a7-e08ef20ceed7"
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
Atomix = "a9b6321e-bd34-4604-b9c9-b65b8de01458"
Bessels = "0e736298-9ec6-45e8-9647-e4fc86a2fe38"
Bumper = "8ce10254-0962-460f-a3d8-1f77fea1446e"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
GPUArraysCore = "46192b85-c4d5-4398-a991-12ede77f4527"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Static = "aedffcd0-7271-4cad-89d0-dc628f76c6d3"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[weakdeps]
AMDGPU = "21141c5a-9bdb-4563-92ae-f87d6854732e"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"

[extensions]
NonuniformFFTsAMDGPUExt = ["AMDGPU"]
NonuniformFFTsCUDAExt = ["CUDA"]

[compat]
AMDGPU = "1.0.5"
AbstractFFTs = "1.5.0"
AbstractNFFTs = "0.8.2"
Adapt = "4.0.4"
Atomix = "0.1.0"
Bessels = "0.2"
Bumper = "0.6, 0.7"
CUDA = "5.5"
FFTW = "1.7"
GPUArraysCore = "0.1.6, 0.2"
KernelAbstractions = "0.9.25"
LinearAlgebra = "1.9"
PrecompileTools = "1.2"
Static = "0.8, 1"
StaticArrays = "1.7"
StructArrays = "0.6"
TimerOutputs = "0.5"
julia = "1.9"
