[deps]
AbstractFFTs = "621f4979-c628-5d54-868e-fcf4e3e8185c"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
NonuniformFFTs = "cd96f58b-6017-4a02-bb9e-f4d81626177f"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
